alias d=docker_fzf
alias dps='docker_ps_fzf'
alias de='docker_fzf exec'
alias dpu='docker_fzf pull'
alias dstata='docker stats'
alias dtop='docker top $(docker_ps_fzf)'

alias dcin='docker inspect $(docker_ps_fzf)'
alias dcls='docker ls $(docker_ps_fzf)'
alias dlog='docker logs $(docker_ps_fzf)'
alias dpo='docker port $(docker_ps_fzf)'
alias drm='docker rm $(docker_ps_fzf)'
alias dst='docker start $(docker_ps_fzf)'
alias dstp='docker stop $(docker_ps_fzf)'
alias drs='docker restart $(docker_ps_fzf)'
alias dstat='docker stats $(docker_ps_fzf)'

alias dco='docker_compose_commands'
alias dce='docker_compose_commands "" edit'
alias dcup='docker_compose_up'
alias dcupd='docker_compose_up -d'
alias dcupf='docker compose -f $(docker_compose_fzf) up -d --force-recreate'
alias dcdn='docker compose -f $(docker_compose_fzf) down'
alias dcl='docker_compose_commands logs'
alias dclf='docker compose -f $(docker_compose_fzf) logs -f'
alias dclF='docker compose -f $(docker_compose_fzf) logs -f --tail 0'
alias dcpull='docker compose -f $(docker_compose_fzf) pull'
alias dcst='docker compose -f $(docker_compose_fzf) start'
alias dcstp='docker compose -f $(docker_compose_fzf) stop'

alias dib='docker_image_commands build'
alias dii='docker_image_commands inspect'
alias dils='docker_image_commands ls'
alias dipu='docker_image_commands push'
alias dipru='docker_image_commands prune'
alias dirm='docker_image_commands rm'
alias ditag='docker_image_commands tag'

alias dnc='docker_network_commands create'
alias dncn='docker_network_commands connect'
alias dndcn='docker_network_commands disconnect'
alias dni='docker_network_commands inspect'
alias dnls='docker_network_commands ls'
alias dnrm='docker_network_commands rm'
alias dnpru='docker_network_commands prune'

alias dvi='docker_volume_commands inspect'
alias dvls='docker_volume_commands ls'
alias dvrm='docker_volume_commands rm'
alias dvpru='docker_volume_commands prune'

alias ddf='docker system df'
alias ddfv='docker system df -v'
alias devts='docker_system_commands events'
alias dinfo='docker_system_commands info'
alias dpru='docker_system_commands prune'
