ZSH_FZF_HISTORY_SEARCH_FZF_EXTRA_ARGS='--height 40% --border=rounded --border-label=History'
ZSH_FZF_HISTORY_SEARCH_FZF_QUERY_PREFIX=''
ZSH_FZF_HISTORY_SEARCH_END_OF_LINE=true
ZSH_FZF_HISTORY_SEARCH_EVENT_NUMBERS=0
ZSH_FZF_HISTORY_SEARCH_DATES_IN_SEARCH=1
ZSH_FZF_HISTORY_SEARCH_REMOVE_DUPLICATES=''
