-- Hyprland Wiki Links
-- Animation - https://wiki.hyprland.org/Configuring/Animations/
-- Decoration - https://wiki.hyprland.org/Configuring/Variables/#decoration

-- Sourcing colors generated by wallust
local colors = require("wallust.wallust-hyprland")

hl.config({
  general = {
    border_size = 2,
    gaps_in = 6,
    gaps_out = 8,
    col = {
      active_border = colors.color12,
      inactive_border = colors.color10,
    },
  },
  decoration = {
    rounding = 10,
    active_opacity = 1.0,
    inactive_opacity = 0.9,
    fullscreen_opacity = 1.0,
    dim_inactive = true,
    dim_strength = 0.1,
    dim_special = 0.8,
    shadow = {
      enabled = true,
      range = 6,
      render_power = 1,
      color = colors.color12,
      color_inactive = colors.color2,
    },
    blur = {
      enabled = true,
      size = 6,
      passes = 2,
      ignore_opacity = true,
      new_optimizations = true,
      special = true,
    },
  },
  group = {
    col = {
      border_active = colors.color15,
    },
    groupbar = {
      col = {
        active = colors.color0,
      },
    },
  },
})
